refresh_rate: 30 seconds
appenders:
  stdout:
    kind: console
  lib:
    kind: file
    path: "log/lib.log"
    encoder:
      pattern: "{d} - {m}{n}"
  files:
    kind: file
    path: "log/files.log"
    encoder:
      pattern: "{m}{n}"
root:
  level: info
  appenders:
    - stdout
loggers:
  lib:
    level: debug
    appenders:
      - lib
    additive: false
  file_log:
    level: debug
    appenders:
      - files
    additive: false