refresh_rate: 30 seconds
appenders:
  stdout:
    kind: console
  print:
    kind: console
    encoder:
      pattern: "{l} - {m}{n}"
  log:
    kind: file
    path: "log/ruckup.log"
  lib:
    kind: file
    path: "log/lib.log"
    encoder:
      pattern: "{d} - {m}{n}"
root:
  level: info
  appenders:
    - stdout
loggers:
  print:
    level: debug
    appenders:
      - print
    additive: false
  print::important:
    level: info
    appenders:
      - log
  lib:
    level: debug
    appenders:
      - lib
    additive: false