refresh_rate: 30 seconds
appenders:
  stdout:
    kind: console
  lib:
    kind: file
    path: "log/lib.log"
    encoder:
      pattern: "{d} - {m}{n}"
root:
  level: debug
  appenders:
    - stdout
loggers:
  lib:
    level: debug
    appenders:
      - lib
    additive: false